/*
   Copyright 2021 MediaExchange.io

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package newznab

import (
	"bytes"
	"encoding/xml"
	"golang.org/x/net/html/charset"
)

// Newznab represents the RSS feed returned from a query. The struct was generated by pasting
// testdata/search-results.xml into https://www.onlinetool.io/xmltogo/
type Newznab struct {
	XMLName xml.Name `xml:"rss" json:"-"`
	Text    string   `xml:",chardata" json:"-"`
	Version string   `xml:"version,attr"`
	Atom    string   `xml:"atom,attr"`
	Newznab string   `xml:"newznab,attr"`
	Channel struct {
		Text string `xml:",chardata" json:"-"`
		Link struct {
			Text string `xml:",chardata"`
			Href string `xml:"href,attr"`
			Rel  string `xml:"rel,attr"`
			Type string `xml:"type,attr"`
		} `xml:"link"`
		Title       string `xml:"title"`
		Description string `xml:"description"`
		Language    string `xml:"language"`
		WebMaster   string `xml:"webMaster"`
		Category    string `xml:"category"`
		Image       struct {
			Text        string `xml:",chardata" json:"-"`
			URL         string `xml:"url"`
			Title       string `xml:"title"`
			Link        string `xml:"link"`
			Description string `xml:"description"`
		} `xml:"image"`
		Response struct {
			Text   string `xml:",chardata" json:"-"`
			Offset string `xml:"offset,attr"`
			Total  string `xml:"total,attr"`
		} `xml:"response"`
		Item []struct {
			Text  string `xml:",chardata" json:"-"`
			Title string `xml:"title"`
			Guid  struct {
				Text        string `xml:",chardata"`
				IsPermaLink string `xml:"isPermaLink,attr"`
			} `xml:"guid"`
			Link        string `xml:"link"`
			Comments    string `xml:"comments"`
			PubDate     string `xml:"pubDate"`
			Category    string `xml:"category"`
			Description string `xml:"description"`
			Enclosure   struct {
				Text   string `xml:",chardata" json:"-"`
				URL    string `xml:"url,attr"`
				Length string `xml:"length,attr"`
				Type   string `xml:"type,attr"`
			} `xml:"enclosure"`
			Attr []struct {
				Text  string `xml:",chardata" json:"-"`
				Name  string `xml:"name,attr"`
				Value string `xml:"value,attr"`
			} `xml:"attr"`
		} `xml:"item"`
	} `xml:"channel"`
}

// fromXML decodes Newznab XML content to an Newznab struct.
func NewznabFromXml(data []byte) (newznab Newznab, err error) {
	// Some Newznab files use iso-8859-1 encoding instead of UTF-8. This
	// implementation was taken from https://stackoverflow.com/a/32224438
	reader := bytes.NewReader(data)
	decoder := xml.NewDecoder(reader)
	decoder.CharsetReader = charset.NewReaderLabel
	err = decoder.Decode(&newznab)
	return
}
